--- 
roles: 
  admin: 
    can: 
      create: []

      read: 
      - Tune
      - Concerto
      write: []

      manage: 
      - Article
      delete: 
      - Article
    cannot: 
      create: []

      read: 
      - Article
      write: []

      delete: 
      - Article
      manage: 
      - Comment
  user: 
    can: 
      create: 
      - Improvisation
role_groups: 
