--- 
roles: 
  admin: 
    can: 
      create: 
      - Post
      read: []

      write: []

      manage: []

      delete: []

    cannot: 
      create: []

      read: []

      write: []

      delete: []

      manage: []

  user: 
    can: 
      create: []

      read: []

    cannot: 
      create: []

role_groups: 
