--- 
roles: 
  admin: 
    can: 
      create: 
      - Comment
      - Post
      read: 
      - Tune
      - Concerto
      - ""
      - Song
    cannot: 
      create: []

      read: []

  user: 
    can: 
      create: 
      - Improvisation
role_groups: 
